# Generated by Django 5.1.6 on 2025-04-29 03:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "recipe_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("instructions", models.TextField()),
                ("picture", models.ImageField(upload_to="recipes/")),
                ("protein", models.PositiveIntegerField()),
                ("calories", models.PositiveIntegerField()),
                ("fat", models.PositiveIntegerField()),
                ("carbohydrates", models.PositiveIntegerField()),
                ("ingredients", models.TextField()),
                (
                    "cook_time",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0.0)]
                    ),
                ),
                ("cuisine", models.CharField(max_length=100)),
            ],
        ),
    ]
