# Generated by Django 5.2 on 2025-05-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_alter_customrecipe_name_alter_premaderecipe_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customrecipe",
            name="name",
            field=models.CharField(
                default="My Recipe Name", max_length=200, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="premaderecipe",
            name="name",
            field=models.CharField(
                default="My Recipe Name", max_length=200, unique=True
            ),
        ),
    ]
