# Generated by Django 5.2 on 2025-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customrecipe_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklymealplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, null=True, related_name='meal_plans', to='main_app.premaderecipe'),
        ),
    ]
