BEGIN;
--
-- Create model PremadeRecipe
--
CREATE TABLE "main_app_premaderecipe" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NULL, "description" text NULL, "instructions" text NULL, "picture" varchar(100) NULL, "protein" integer NULL CHECK ("protein" >= 0), "calories" integer NULL CHECK ("calories" >= 0), "fat" integer NULL CHECK ("fat" >= 0), "carbohydrates" integer NULL CHECK ("carbohydrates" >= 0), "ingredients" text NULL, "cook_time" double precision NULL, "cuisine" varchar(100) NULL);
--
-- Create model CustomRecipe
--
CREATE TABLE "main_app_customrecipe" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NULL, "description" text NULL, "instructions" text NULL, "picture" varchar(100) NULL, "protein" integer NULL CHECK ("protein" >= 0), "calories" integer NULL CHECK ("calories" >= 0), "fat" integer NULL CHECK ("fat" >= 0), "carbohydrates" integer NULL CHECK ("carbohydrates" >= 0), "ingredients" text NULL, "cook_time" double precision NULL, "cuisine" varchar(100) NULL, "user_id" integer NOT NULL);
--
-- Create model WeeklyMealPlan
--
CREATE TABLE "main_app_weeklymealplan" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "start_date" date NOT NULL, "user_id" integer NOT NULL);
CREATE TABLE "main_app_weeklymealplan_recipes" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "weeklymealplan_id" bigint NOT NULL, "customrecipe_id" bigint NOT NULL);
ALTER TABLE "main_app_customrecipe" ADD CONSTRAINT "main_app_customrecipe_user_id_ee34dc44_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_customrecipe_user_id_ee34dc44" ON "main_app_customrecipe" ("user_id");
ALTER TABLE "main_app_weeklymealplan" ADD CONSTRAINT "main_app_weeklymealplan_user_id_start_date_859e20b5_uniq" UNIQUE ("user_id", "start_date");
ALTER TABLE "main_app_weeklymealplan" ADD CONSTRAINT "main_app_weeklymealplan_user_id_47b2c928_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_weeklymealplan_user_id_47b2c928" ON "main_app_weeklymealplan" ("user_id");
ALTER TABLE "main_app_weeklymealplan_recipes" ADD CONSTRAINT "main_app_weeklymealplan__weeklymealplan_id_custom_6f595cf4_uniq" UNIQUE ("weeklymealplan_id", "customrecipe_id");
ALTER TABLE "main_app_weeklymealplan_recipes" ADD CONSTRAINT "main_app_weeklymealp_weeklymealplan_id_0783c140_fk_main_app_" FOREIGN KEY ("weeklymealplan_id") REFERENCES "main_app_weeklymealplan" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_app_weeklymealplan_recipes" ADD CONSTRAINT "main_app_weeklymealp_customrecipe_id_d2643c44_fk_main_app_" FOREIGN KEY ("customrecipe_id") REFERENCES "main_app_customrecipe" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_weeklymealplan_recipes_weeklymealplan_id_0783c140" ON "main_app_weeklymealplan_recipes" ("weeklymealplan_id");
CREATE INDEX "main_app_weeklymealplan_recipes_customrecipe_id_d2643c44" ON "main_app_weeklymealplan_recipes" ("customrecipe_id");
COMMIT;
