BEGIN;
--
-- Create model WeeklyMealPlanEntry
--
CREATE TABLE "main_app_weeklymealplanentry" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "day" varchar(20) NOT NULL, "meal_time" varchar(20) NOT NULL, "meal_plan_id" bigint NOT NULL, "recipe_id" bigint NOT NULL);
ALTER TABLE "main_app_weeklymealplanentry" ADD CONSTRAINT "main_app_weeklymealp_meal_plan_id_664e9123_fk_main_app_" FOREIGN KEY ("meal_plan_id") REFERENCES "main_app_weeklymealplan" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "main_app_weeklymealplanentry" ADD CONSTRAINT "main_app_weeklymealp_recipe_id_5e7aca17_fk_main_app_" FOREIGN KEY ("recipe_id") REFERENCES "main_app_premaderecipe" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "main_app_weeklymealplanentry_meal_plan_id_664e9123" ON "main_app_weeklymealplanentry" ("meal_plan_id");
CREATE INDEX "main_app_weeklymealplanentry_recipe_id_5e7aca17" ON "main_app_weeklymealplanentry" ("recipe_id");
COMMIT;
